// Generated by An Kun

const { execSync } = require('child_process');
const fs = require('fs');

console.log('🚀 Starting Vercel build...');

try {
  // Build webapp only (main application)
  console.log('🏗️ Building webapp...');
  process.chdir('packages/webapp');
  execSync('npm run build', { stdio: 'inherit' });
  
  console.log('✅ Build completed successfully!');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}
