// Generated by An Kun
import type { Config } from 'drizzle-kit'
import { getDatabaseConfig } from './packages/server/src/config/database'

const config = getDatabaseConfig()

export default {
  schema: './packages/server/src/database/schema.ts',
  out: './packages/server/src/migrations',
  driver: 'pg',
  dbCredentials: {
    connectionString: config.database_url
  },
  verbose: true,
  strict: true
} satisfies Config
