// Generated by An Kun

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Configure Next.js to work with Vite build output
  experimental: {
    appDir: false
  },
  // Export as static files since we're using Vite
  output: 'export',
  trailingSlash: true,
  skipTrailingSlashRedirect: true,
  images: {
    unoptimized: true
  },
  // Custom build directory
  distDir: 'dist',
  // Disable Next.js default pages since we use Vite
  pageExtensions: [],
  // Custom webpack config to skip build
  webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
    // Skip webpack processing since Vite handles it
    return config;
  }
}

module.exports = nextConfig
