export * from './answer-to-html'
export * from './answer-to-api-object'
export * from './answer-to-plain'
export * from './answer-to-json'
export * from './hidden-fields-to-html'
export * from './field-values-to-answer'
export * from './fields-to-validate-rules'
export * from './validate'
export * from './html-utils'
export * from './flatten-fields'
export * from './validate-condition'
export * from './validate-payload'
export * from './apply-logic-to-fields'
export * from './consts'
export * from './helper'

// Generated by An Kun

import { FormStatus } from '@heyform-inc/shared-types-enums'

export function process_form_answer(answer: any): any {
  return {
    processed_answer: answer,
    timestamp: new Date().toISOString()
  }
}

export function validate_form_submission(data: any): boolean {
  return data && typeof data === 'object'
}
