// Generated by An Kun

import _ from 'lodash'

export function format_email(email: string): string {
  return email.toLowerCase().trim()
}

export function generate_id(): string {
  return _.uniqueId('heyform_')
}

export function is_valid_url(url: string): boolean {
  try {
    new URL(url)
    return true
  } catch {
    return false
  }
}

export function sanitize_string(input: string): string {
  return input.replace(/[<>]/g, '')
}

export function format_date(date: Date): string {
  return date.toISOString().split('T')[0]
}
