// Generated by An Kun

export function validate_required(value: any): boolean {
  return value !== null && value !== undefined && value !== ''
}

export function validate_email(email: string): boolean {
  const email_regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return email_regex.test(email)
}
