// Generated by An Kun
import { pgTable, text, timestamp, boolean, integer, uuid, jsonb, varchar } from 'drizzle-orm/pg-core'

export const users_table = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: varchar('email', { length: 255 }).notNull().unique(),
  password_hash: text('password_hash'),
  first_name: varchar('first_name', { length: 100 }),
  last_name: varchar('last_name', { length: 100 }),
  avatar_url: text('avatar_url'),
  is_email_verified: boolean('is_email_verified').default(false),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
  deleted_at: timestamp('deleted_at')
})

export const workspaces_table = pgTable('workspaces', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  slug: varchar('slug', { length: 100 }).notNull().unique(),
  logo_url: text('logo_url'),
  owner_id: uuid('owner_id').references(() => users_table.id),
  settings: jsonb('settings'),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
  deleted_at: timestamp('deleted_at')
})

export const projects_table = pgTable('projects', {
  id: uuid('id').primaryKey().defaultRandom(),
  name: varchar('name', { length: 255 }).notNull(),
  workspace_id: uuid('workspace_id').references(() => workspaces_table.id),
  created_by: uuid('created_by').references(() => users_table.id),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
  deleted_at: timestamp('deleted_at')
})

export const forms_table = pgTable('forms', {
  id: uuid('id').primaryKey().defaultRandom(),
  title: varchar('title', { length: 255 }).notNull(),
  description: text('description'),
  project_id: uuid('project_id').references(() => projects_table.id),
  form_schema: jsonb('form_schema'),
  settings: jsonb('settings'),
  status: varchar('status', { length: 20 }).default('draft'),
  created_by: uuid('created_by').references(() => users_table.id),
  created_at: timestamp('created_at').defaultNow(),
  updated_at: timestamp('updated_at').defaultNow(),
  deleted_at: timestamp('deleted_at')
})

export const submissions_table = pgTable('submissions', {
  id: uuid('id').primaryKey().defaultRandom(),
  form_id: uuid('form_id').references(() => forms_table.id),
  submission_data: jsonb('submission_data'),
  user_agent: text('user_agent'),
  ip_address: varchar('ip_address', { length: 45 }),
  created_at: timestamp('created_at').defaultNow()
})

export const workspace_members_table = pgTable('workspace_members', {
  id: uuid('id').primaryKey().defaultRandom(),
  workspace_id: uuid('workspace_id').references(() => workspaces_table.id),
  user_id: uuid('user_id').references(() => users_table.id),
  role: varchar('role', { length: 20 }).default('member'),
  invited_at: timestamp('invited_at').defaultNow(),
  joined_at: timestamp('joined_at')
})
