// Generated by An Kun
import { StackServerApp } from "@stackframe/stack";

if (!process.env.STACK_SECRET_SERVER_KEY) {
  throw new Error('STACK_SECRET_SERVER_KEY environment variable is required');
}

export const stack_server_app = new StackServerApp({
  tokenStore: "nextjs-cookie",
  secretServerKey: process.env.STACK_SECRET_SERVER_KEY,
});

export async function validateStackToken(token: string) {
  try {
    const user = await stack_server_app.getUser({ accessToken: token });
    return user;
  } catch (error) {
    console.error('Stack auth validation failed:', error);
    return null;
  }
}

export async function getStackUser(user_id: string) {
  try {
    const user = await stack_server_app.getUser({ userId: user_id });
    return user;
  } catch (error) {
    console.error('Failed to get Stack user:', error);
    return null;
  }
}
