// Generated by An Kun

import { AddTodoForm } from "../../components/todo-add-form";
import { TodosList } from "../../components/todos-list";
import { stack_server_app } from "../../lib/stack-server";

export default async function TodosPage() {
  const user = await stack_server_app.getUser();

  if (!user) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="max-w-md mx-auto bg-white rounded-lg shadow-md p-6">
          <h2 className="text-2xl font-bold text-center text-gray-900 mb-4">
            Welcome to HeyForm Tasks
          </h2>
          <p className="text-gray-600 text-center mb-6">
            Please sign in to manage your tasks and forms.
          </p>
          <div className="space-y-3">
            <a
              href="/auth/signin"
              className="w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 transition-colors text-center block"
            >
              Sign In
            </a>
            <a
              href="/auth/signup"
              className="w-full bg-gray-100 text-gray-700 py-2 px-4 rounded-md hover:bg-gray-200 transition-colors text-center block"
            >
              Sign Up
            </a>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="bg-white shadow-sm border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <h1 className="text-xl font-semibold text-gray-900">
              HeyForm Tasks
            </h1>
            <div className="flex items-center space-x-4">
              <span className="text-sm text-gray-700">
                {user.displayName || user.primaryEmail}
              </span>
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Add Todo Form */}
          <div className="lg:col-span-1">
            <AddTodoForm />
          </div>
          
          {/* Todos List */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-lg shadow-sm p-6">
              <TodosList />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
