// Generated by An Kun

interface ClientEnvironmentConfig {
  stack_project_id: string
  stack_publishable_key: string
  api_base_url: string
  graphql_endpoint: string
  node_env: string
  is_development: boolean
  is_production: boolean
}

// Only use environment variables that are safe for client-side
export const getClientEnvironment = (): ClientEnvironmentConfig => {
  const config = {
    stack_project_id: import.meta.env.VITE_STACK_PROJECT_ID || '',
    stack_publishable_key: import.meta.env.VITE_STACK_PUBLISHABLE_CLIENT_KEY || '',
    api_base_url: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3001',
    graphql_endpoint: import.meta.env.VITE_GRAPHQL_ENDPOINT || '/graphql',
    node_env: import.meta.env.NODE_ENV || 'development',
    is_development: import.meta.env.NODE_ENV === 'development',
    is_production: import.meta.env.NODE_ENV === 'production'
  }

  // Validate required client variables
  if (!config.stack_project_id) {
    console.warn('⚠️ VITE_STACK_PROJECT_ID is not configured')
  }
  if (!config.stack_publishable_key) {
    console.warn('⚠️ VITE_STACK_PUBLISHABLE_CLIENT_KEY is not configured')
  }

  return config
}

// Export for use in components
export const CLIENT_ENV = getClientEnvironment()

// Never expose these server variables to client
const FORBIDDEN_CLIENT_VARS = [
  'DATABASE_URL',
  'POSTGRES_URL', 
  'PGPASSWORD',
  'STACK_SECRET_SERVER_KEY',
  'JWT_SECRET'
]

// Development warning for accidentally exposed variables
if (CLIENT_ENV.is_development) {
  FORBIDDEN_CLIENT_VARS.forEach(var_name => {
    if (import.meta.env[var_name]) {
      console.error(`🚨 SECURITY WARNING: ${var_name} should not be exposed to client!`)
    }
  })
}
