// Generated by An Kun
import { Request, Response, NextFunction } from 'express';
import { testDatabaseConnection } from '../utils/database';

export async function validateDatabaseConnection(req: Request, res: Response, next: NextFunction) {
  try {
    const is_connected = await testDatabaseConnection();
    
    if (!is_connected) {
      return res.status(503).json({
        error: 'Database connection failed',
        message: 'Unable to connect to the database'
      });
    }
    
    next();
  } catch (error) {
    console.error('Database validation middleware error:', error);
    return res.status(500).json({
      error: 'Internal server error',
      message: 'Database validation failed'
    });
  }
}

export function addDatabaseHeaders(req: Request, res: Response, next: NextFunction) {
  res.setHeader('X-Database-Provider', 'Neon-Postgres');
  res.setHeader('X-Generated-By', 'An-Kun');
  next();
}
