// Generated by An Kun

import { Request, Response, NextFunction } from 'express';
import { neon } from '@neondatabase/serverless';

const sql = neon(process.env.DATABASE_URL!);

export async function validateDatabaseConnection(
  req: Request, 
  res: Response, 
  next: NextFunction
) {
  try {
    // Test database connection
    await sql`SELECT 1`;
    
    // Add database info to response headers
    res.setHeader('X-Database-Status', 'connected');
    res.setHeader('X-Database-Provider', 'neon-postgres');
    
    next();
  } catch (error) {
    console.error('Database middleware error:', error);
    
    res.status(503).json({
      error: 'Database unavailable',
      message: 'Unable to connect to the database',
      timestamp: new Date().toISOString()
    });
  }
}

export function addDatabaseHeaders(
  req: Request, 
  res: Response, 
  next: NextFunction
) {
  res.setHeader('X-Powered-By-Database', 'Neon-Postgres');
  res.setHeader('X-Generated-By', 'An-Kun');
  next();
}
