// Generated by An Kun

import { stack_server_app } from "../lib/stack-server";

export async function Header() {
  const user = await stack_server_app.getUser();

  return (
    <header className="bg-white shadow-sm border-b border-gray-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center">
            <h1 className="text-xl font-semibold text-gray-900">
              HeyForm Tasks
            </h1>
          </div>
          
          <div className="flex items-center space-x-4">
            {user ? (
              <>
                <div className="flex items-center space-x-2">
                  {user.profileImageUrl && (
                    <img
                      src={user.profileImageUrl}
                      alt="Profile"
                      className="h-8 w-8 rounded-full"
                    />
                  )}
                  <span className="text-sm text-gray-700">
                    {user.displayName || user.primaryEmail}
                  </span>
                </div>
                
                <a
                  href="/auth/signout"
                  className="text-sm text-gray-500 hover:text-gray-700"
                >
                  Sign Out
                </a>
              </>
            ) : (
              <div className="space-x-2">
                <a
                  href="/auth/signin"
                  className="text-sm text-blue-600 hover:text-blue-700"
                >
                  Sign In
                </a>
                <a
                  href="/auth/signup"
                  className="text-sm bg-blue-600 text-white px-3 py-1 rounded hover:bg-blue-700"
                >
                  Sign Up
                </a>
              </div>
            )}
          </div>
        </div>
      </div>
    </header>
  );
}
