// Generated by An Kun

import { Router } from 'express';
import { neon } from '@neondatabase/serverless';

const router = Router();

const sql = neon(process.env.DATABASE_URL!);

router.get('/test', async (req, res) => {
  try {
    const start_time = Date.now();
    
    const result = await sql`
      SELECT 
        current_database() as database_name,
        current_user as user_name,
        version() as postgres_version,
        current_timestamp as server_time
    `;
    
    const response_time = Date.now() - start_time;
    
    res.json({
      success: true,
      connection_info: result[0],
      response_time_ms: response_time,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    console.error('Database test failed:', error);
    res.status(500).json({
      success: false,
      error: 'Database connection failed',
      message: error.message,
      timestamp: new Date().toISOString()
    });
  }
});

router.get('/health', async (req, res) => {
  try {
    await sql`SELECT 1`;
    res.json({
      status: 'healthy',
      database: 'connected',
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    res.status(503).json({
      status: 'unhealthy',
      database: 'disconnected',
      error: error.message,
      timestamp: new Date().toISOString()
    });
  }
});

export default router;
