// Generated by An Kun
import { Router } from 'express';
import { getDatabaseInfo, getConnectionStatus } from '../utils/database';

const router = Router();

router.get('/health', async (req, res) => {
  try {
    const connection_status = await getConnectionStatus();
    const database_info = await getDatabaseInfo();
    
    const health_data = {
      status: 'healthy',
      timestamp: new Date().toISOString(),
      database: {
        ...connection_status,
        info: database_info
      },
      environment: {
        node_env: process.env.NODE_ENV,
        stack_project_id: process.env.NEXT_PUBLIC_STACK_PROJECT_ID
      }
    };
    
    res.json(health_data);
  } catch (error) {
    res.status(500).json({
      status: 'unhealthy',
      error: error.message,
      timestamp: new Date().toISOString()
    });
  }
});

export default router;
