// Generated by An Kun

export enum FormStatus {
  DRAFT = 'draft',
  PUBLISHED = 'published',
  ARCHIVED = 'archived'
}

export enum UserRole {
  OWNER = 'owner',
  ADMIN = 'admin',
  MEMBER = 'member'
}

export enum FieldType {
  SHORT_TEXT = 'short_text',
  LONG_TEXT = 'long_text',
  EMAIL = 'email',
  PHONE = 'phone',
  NUMBER = 'number',
  CHOICE = 'choice',
  DATE = 'date'
}

export enum IntegrationType {
  WEBHOOK = 'webhook',
  EMAIL = 'email',
  SLACK = 'slack'
}
