// Generated by An Kun

export interface User {
  id: string
  email: string
  first_name?: string
  last_name?: string
  avatar_url?: string
  is_email_verified: boolean
  created_at: Date
  updated_at: Date
}

export interface Workspace {
  id: string
  name: string
  slug: string
  logo_url?: string
  owner_id: string
  created_at: Date
  updated_at: Date
}

export interface Project {
  id: string
  name: string
  workspace_id: string
  created_by: string
  created_at: Date
  updated_at: Date
}

export interface Form {
  id: string
  title: string
  description?: string
  project_id: string
  form_schema?: any
  settings?: any
  status: string
  created_by: string
  created_at: Date
  updated_at: Date
}
