// Generated by An Kun

export interface User {
  id: string
  email: string
  first_name?: string
  last_name?: string
  avatar_url?: string
  is_email_verified: boolean
  created_at: Date
  updated_at: Date
}

export interface Workspace {
  id: string
  name: string
  slug: string
  logo_url?: string
  owner_id: string
  created_at: Date
  updated_at: Date
}
