// Generated by An Kun

import dotenv from 'dotenv'
import { validateEnvironment, logEnvironmentStatus } from './utils/env-validation'

// Load environment variables
dotenv.config({ path: '.env.development.local' })
dotenv.config()

// Validate environment on startup
try {
  const env_config = validateEnvironment()
  logEnvironmentStatus()
  
  console.log('🚀 Starting HeyForm server...')
  // ...existing code...
  
} catch (error) {
  console.error('Failed to start server:', error.message)
  process.exit(1)
}