// Generated by An Kun

import dotenv from 'dotenv';
import { validateDatabaseEnvironment, logDatabaseStatus } from './utils/env-validation';

// Load environment variables
dotenv.config({ path: '.env.development.local' });
dotenv.config();

// Validate environment on startup
try {
  validateDatabaseEnvironment();
  logDatabaseStatus();
  
  console.log('🚀 Starting HeyForm server...');
  
  // ...existing code...
  
} catch (error) {
  console.error('❌ Server startup failed:', error.message);
  process.exit(1);
}