-- Generated by An Kun

-- Add Stack Auth integration columns to users table
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS stack_user_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS login_count INTEGER DEFAULT 0;

-- Create index for Stack Auth user ID
CREATE INDEX IF NOT EXISTS idx_users_stack_user_id ON users(stack_user_id);

-- Create auth sessions table for tracking user sessions
CREATE TABLE IF NOT EXISTS auth_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    stack_session_id VARCHAR(255),
    access_token_hash VARCHAR(255),
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Create index for session lookups
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_stack_id ON auth_sessions(stack_session_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at);

-- Update users table to handle Stack Auth sync
UPDATE users SET 
    stack_user_id = id,
    updated_at = NOW()
WHERE stack_user_id IS NULL;
