-- Generated by An Kun

-- Create neon_auth schema for Stack Auth integration
CREATE SCHEMA IF NOT EXISTS neon_auth;

-- Users table for Neon Auth
CREATE TABLE IF NOT EXISTS neon_auth.users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    stack_user_id VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    display_name VARCHAR(255),
    profile_image_url TEXT,
    is_email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- TODOs table for example implementation
CREATE TABLE IF NOT EXISTS neon_auth.todos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    completed BOOLEAN DEFAULT FALSE,
    user_id UUID REFERENCES neon_auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Forms ownership table
CREATE TABLE IF NOT EXISTS neon_auth.form_owners (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    form_id UUID REFERENCES forms(id) ON DELETE CASCADE,
    user_id UUID REFERENCES neon_auth.users(id) ON DELETE CASCADE,
    role VARCHAR(50) DEFAULT 'owner',
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(form_id, user_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_neon_auth_users_stack_id ON neon_auth.users(stack_user_id);
CREATE INDEX IF NOT EXISTS idx_neon_auth_users_email ON neon_auth.users(email);
CREATE INDEX IF NOT EXISTS idx_neon_auth_todos_user_id ON neon_auth.todos(user_id);
CREATE INDEX IF NOT EXISTS idx_neon_auth_form_owners_form_id ON neon_auth.form_owners(form_id);
CREATE INDEX IF NOT EXISTS idx_neon_auth_form_owners_user_id ON neon_auth.form_owners(user_id);

-- Insert sample data
INSERT INTO neon_auth.users (stack_user_id, email, display_name, is_email_verified) 
VALUES 
    ('sample_user_1', 'user1@example.com', 'Sample User 1', TRUE),
    ('sample_user_2', 'user2@example.com', 'Sample User 2', TRUE)
ON CONFLICT (email) DO NOTHING;
