// Generated by An Kun

/** @type {import('next').NextConfig} */
const nextConfig = {
  // Disable Next.js since we're using Vite
  experimental: {
    appDir: false
  },
  // Export as static files
  output: 'export',
  trailingSlash: true,
  // Skip build step since Vite handles it
  skipTrailingSlashRedirect: true,
  images: {
    unoptimized: true
  }
}

module.exports = nextConfig
