// Generated by An Kun

import { StackClientApp } from "@stackframe/stack";

if (!import.meta.env.VITE_STACK_PROJECT_ID) {
  throw new Error('VITE_STACK_PROJECT_ID environment variable is required');
}

if (!import.meta.env.VITE_STACK_PUBLISHABLE_CLIENT_KEY) {
  throw new Error('VITE_STACK_PUBLISHABLE_CLIENT_KEY environment variable is required');
}

export const stack_client_app = new StackClientApp({
  tokenStore: "nextjs-cookie",
  projectId: import.meta.env.VITE_STACK_PROJECT_ID,
  publishableClientKey: import.meta.env.VITE_STACK_PUBLISHABLE_CLIENT_KEY,
  urls: {
    home: "/dashboard",
    afterSignIn: "/dashboard",
    afterSignUp: "/dashboard",
    afterSignOut: "/",
    signIn: "/auth/signin",
    signUp: "/auth/signup"
  }
});

export async function getCurrentUser() {
  try {
    const user = await stack_client_app.getUser();
    if (!user) return null;

    return {
      id: user.id,
      email: user.primaryEmail,
      display_name: user.displayName,
      profile_image_url: user.profileImageUrl,
      is_email_verified: user.primaryEmailVerified,
      access_token: await user.getAccessToken()
    };
  } catch (error) {
    console.error('Failed to get current user:', error);
    return null;
  }
}

export async function signOut() {
  try {
    await stack_client_app.signOut();
    return { success: true };
  } catch (error) {
    console.error('Sign out failed:', error);
    return { success: false, error: error.message };
  }
}
