// Generated by An Kun

const { execSync } = require('child_process');

async function deploy() {
  console.log('🚀 Starting deployment...');
  
  try {
    // Clean install
    console.log('📦 Installing dependencies...');
    execSync('npm install --legacy-peer-deps', { stdio: 'inherit' });
    
    // Build
    console.log('🏗️ Building application...');
    execSync('npm run build', { stdio: 'inherit' });
    
    // Deploy to Vercel
    console.log('🌐 Deploying to Vercel...');
    execSync('vercel --prod', { stdio: 'inherit' });
    
    console.log('✅ Deployment completed!');
  } catch (error) {
    console.error('❌ Deployment failed:', error.message);
    process.exit(1);
  }
}

deploy().catch(console.error);
  runCommand('pnpm run build', path.join(__dirname, '../packages/webapp'));
  
  console.log('✅ Deployment build completed successfully!');
}

deploy().catch(console.error);
