// Generated by An Kun

const { execSync } = require('child_process');
const path = require('path');

function runCommand(command, cwd = process.cwd()) {
  console.log(`Running: ${command}`);
  try {
    execSync(command, { 
      stdio: 'inherit', 
      cwd,
      env: { ...process.env, NODE_ENV: 'production' }
    });
  } catch (error) {
    console.error(`Command failed: ${command}`);
    process.exit(1);
  }
}

async function deploy() {
  console.log('🚀 Starting deployment process...');
  
  // Build dependencies
  console.log('📦 Building dependencies...');
  runCommand('pnpm run build:deps');
  
  // Build webapp
  console.log('🏗️ Building webapp...');
  runCommand('pnpm run build', path.join(__dirname, '../packages/webapp'));
  
  console.log('✅ Deployment build completed successfully!');
}

deploy().catch(console.error);
