// Generated by An Kun

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

async function setupEnvironment() {
  console.log('🔧 Setting up environment variables...');
  
  try {
    // Check if Vercel CLI is installed
    try {
      execSync('vercel --version', { stdio: 'pipe' });
    } catch (error) {
      console.log('📦 Installing Vercel CLI...');
      execSync('npm install -g vercel', { stdio: 'inherit' });
    }

    // Pull environment variables from Vercel
    console.log('⬇️ Pulling environment variables from Vercel...');
    execSync('vercel env pull .env.development.local', { stdio: 'inherit' });

    // Verify the file was created
    if (fs.existsSync('.env.development.local')) {
      console.log('✅ Environment variables pulled successfully!');
      
      // Read and validate environment variables
      const env_content = fs.readFileSync('.env.development.local', 'utf8');
      const required_vars = [
        'DATABASE_URL',
        'NEXT_PUBLIC_STACK_PROJECT_ID',
        'STACK_SECRET_SERVER_KEY'
      ];
      
      const missing_vars = required_vars.filter(var_name => 
        !env_content.includes(`${var_name}=`)
      );
      
      if (missing_vars.length > 0) {
        console.log('⚠️ Missing required environment variables:');
        missing_vars.forEach(var_name => console.log(`  - ${var_name}`));
        console.log('\n🔗 Please add these variables in your Vercel dashboard:');
        console.log('   https://vercel.com/dashboard/projects/your-project/settings/environment-variables');
      } else {
        console.log('✅ All required environment variables are present!');
      }
    } else {
      console.error('❌ Failed to create .env.development.local file');
    }

  } catch (error) {
    console.error('❌ Error setting up environment:', error.message);
    console.log('\n💡 Manual setup instructions:');
    console.log('1. Install Vercel CLI: npm install -g vercel');
    console.log('2. Login to Vercel: vercel login');
    console.log('3. Link project: vercel link');
    console.log('4. Pull env vars: vercel env pull .env.development.local');
  }
}

setupEnvironment();
