// Generated by An Kun

const fs = require('fs');

function validateJSON(file_path) {
  try {
    if (!fs.existsSync(file_path)) {
      console.log(`⚠️  ${file_path} not found, skipping...`);
      return true;
    }
    
    const content = fs.readFileSync(file_path, 'utf8');
    JSON.parse(content);
    console.log(`✅ ${file_path} is valid JSON`);
    return true;
  } catch (error) {
    console.error(`❌ ${file_path} has JSON errors:`);
    console.error(`   ${error.message}`);
    return false;
  }
}

const files_to_check = [
  'package.json',
  'packages/webapp/package.json',
  'packages/server/package.json'
];

let all_valid = true;

files_to_check.forEach(file => {
  if (!validateJSON(file)) {
    all_valid = false;
  }
});

if (all_valid) {
  console.log('✅ All checked JSON files are valid!');
  process.exit(0);
} else {
  console.error('❌ Some JSON files have errors');
  process.exit(1);
}
  if (all_valid) {
    console.log('✅ All package.json files are valid!');
  } else {
    console.error('❌ Some package.json files have errors');
    process.exit(1);
  }
}

validateAllPackageJSON();
