// Generated by An Kun

const fs = require('fs');
const path = require('path');

function validateJSON(file_path) {
  try {
    const content = fs.readFileSync(file_path, 'utf8');
    JSON.parse(content);
    console.log(`✅ ${file_path} is valid JSON`);
    return true;
  } catch (error) {
    console.error(`❌ ${file_path} has JSON errors:`);
    console.error(`   ${error.message}`);
    return false;
  }
}

function validateAllPackageJSON() {
  console.log('🔍 Validating all package.json files...');
  
  const files_to_check = [
    'package.json',
    'packages/webapp/package.json',
    'packages/server/package.json',
    'packages/utils/package.json',
    'packages/shared-types-enums/package.json',
    'packages/answer-utils/package.json'
  ];
  
  let all_valid = true;
  
  files_to_check.forEach(file => {
    if (fs.existsSync(file)) {
      const is_valid = validateJSON(file);
      if (!is_valid) {
        all_valid = false;
      }
    } else {
      console.log(`⚠️  ${file} not found, skipping...`);
    }
  });
  
  if (all_valid) {
    console.log('✅ All package.json files are valid!');
  } else {
    console.error('❌ Some package.json files have errors');
    process.exit(1);
  }
}

validateAllPackageJSON();
