// Generated by An Kun

const { execSync } = require('child_process');
const path = require('path');

console.log('🚀 Vercel build starting...');

try {
  // Change to webapp directory
  process.chdir(path.join(__dirname, '..', 'packages', 'webapp'));
  
  // Install and build
  console.log('📦 Installing dependencies...');
  execSync('npm install --legacy-peer-deps', { stdio: 'inherit' });
  
  console.log('🏗️ Building webapp...');
  execSync('npm run build', { stdio: 'inherit' });
  
  console.log('✅ Vercel build completed!');
} catch (error) {
  console.error('❌ Build failed:', error.message);
  process.exit(1);
}
