// Generated by An Kun

const fs = require('fs');
const path = require('path');

function verifyBuild() {
  console.log('🔍 Verifying build output...');
  
  const build_dir = path.join(__dirname, '../packages/webapp/.next');
  
  if (fs.existsSync(build_dir)) {
    console.log('✅ Next.js build directory exists');
    
    const static_dir = path.join(build_dir, 'static');
    if (fs.existsSync(static_dir)) {
      console.log('✅ Static assets generated');
    }
    
    const server_dir = path.join(build_dir, 'server');
    if (fs.existsSync(server_dir)) {
      console.log('✅ Server files generated');
    }
    
    console.log('✅ Build verification passed');
    return true;
  } else {
    console.error('❌ Build directory not found');
    return false;
  }
}

if (!verifyBuild()) {
  process.exit(1);
}
