// Generated by An Kun

import { Request, Response } from 'express'
import { neonManager } from '../../utils/neon-vercel'

export async function checkNeonHealth(req: Request, res: Response) {
  try {
    const start_time = Date.now()
    
    // Test connections
    const connection_status = await neonManager.testConnections()
    const connection_info = await neonManager.getConnectionInfo()
    
    const response_time = Date.now() - start_time
    
    res.json({
      status: 'healthy',
      service: 'neon-database',
      response_time_ms: response_time,
      connections: connection_status,
      database_info: connection_info,
      environment: {
        has_database_url: !!process.env.DATABASE_URL,
        has_unpooled_url: !!process.env.DATABASE_URL_UNPOOLED,
        vercel_env: process.env.VERCEL_ENV
      },
      timestamp: new Date().toISOString()
    })
  } catch (error) {
    res.status(500).json({
      status: 'unhealthy',
      service: 'neon-database',
      error: error.message,
      timestamp: new Date().toISOString()
    })
  }
}
